server:
  port: 8888
  servlet:
    context-path: /main

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useAffectedRows=true
    username: user
    password: user123456
    driver-class-name: com.mysql.cj.jdbc.Driver